[project]
name = "tutu_mlops_test"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "greenlet>=3.5.6",
    "joblib==1.4.2",
    "numpy==2.2.2",
    "pandas==2.2.3",
    "pandas-stubs==2.2.3.250527",
    "pydantic>=2.13.5",
    "scikit-learn==1.6.1",
    "sqlalchemy>=2.0.54",
]

[dependency-groups]
dev = [{ include-group = "lint" }, { include-group = "test" }]
lint = ["mypy>=2.3.1", "ruff>=0.16.8"]
test = [
    "coverage>=7.16.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "pytest-dotenv>=0.5.2",
]

[tool.uv]
default-groups = []

[tool.pytest.ini_options]
env_files = [".env"]
