name: Lint, Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v10

      - name: Install dependencies
        run: uv sync --dev --frozen

      - name: Run Ruff linting
        run: uv run --group lint ruff check

      - name: Run Mypy linting
        run: uv run --group lint mypy ./src

      - name: Run Ruff formatting check
        run: uv run --group lint ruff format --check

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mlops_app:test .

      - name: Pull Postgres images
        run: docker pull postgres:17.5-alpine

      - name: Run tests
        run: docker compose -f ./docker-compose.test.yml up --abort-on-container-exit --exit-code-from mlops_app mlops_app
